### ISSUE TITLE
Organic Results

### ISSUE THREAD

**Issue by Mykhailo-Zub** [dimitryzub/serpapi-blog-posts-archive#171]
1. URL: https://www.ebay.com/sch/i.html?_from=R40&_trksid=p2380057.m570.l1313&_nkw=playstation+5&_sacat=0

![image](https://user-images.githubusercontent.com/64033139/171408505-80c98d88-28cb-4cae-abc0-f2d5063d9466.png)

**Comment by dimitryzub** [comment]
@Mykhailo-Zub thank you for adding the Javascript content plan milestone. You can also get rid of `[Ebay]` if you want to, as we add `eBay` label to each issue so it's understandable that the blog post will be about eBay and it will be more text to type.
