### ISSUE TITLE
Cite Results

### ISSUE THREAD

**Issue by dimitryzub** [dimitryzub/serpapi-blog-posts-archive#174]

**Comment by Mykhailo-Zub** [comment]
what: 
![image](https://user-images.githubusercontent.com/64033139/177721411-4fb88604-fc7e-40e5-8068-ebc167be13c1.png)
how:
![how](https://user-images.githubusercontent.com/64033139/177724872-b5c97fe2-7f65-4fd6-ba63-a18991e4673c.gif)
