### ISSUE TITLE
Local Results

### ISSUE THREAD

**Issue by dimitryzub** [dimitryzub/serpapi-blog-posts-archive#191]

**Comment by Mykhailo-Zub** [comment]
what:
![image](https://user-images.githubusercontent.com/64033139/178459793-d2ea82a9-2415-4dc4-b1f3-427f235a664d.png)
how:
![how](https://user-images.githubusercontent.com/64033139/178461319-ac26ce42-83e3-4a70-ae95-fe8f591e8b61.gif)
